### ISSUE TITLE
バトランレビュー

### ISSUE THREAD

**Issue by hisaju** [kosukein38/training_and_meals#188]
※ 確認後closeしてください

## サービスレビュー

* 既に使われていて素晴らしいですね。
* 筋トレと食事の関連性が薄い（別のサービスが2つ入ってる）印象だったので、組み合わせたカロリー計算などを入れることで連動するような筋トレと食事を登録するメリットが作れるといいのかなと思いました。
* UIもユーザの導線を考えて自然と筋トレと食事の両方を登録できるようなカスタマージャーニーが作れるといいですね。
* あとポップアップが多かったのですが、モバイルは特にポップアップだと使いづらいので、筋トレ登録、食事登録などボタンを最初から分けちゃってもいいかと思います。

## コードレビュー

https://github.com/kosukein38/training_and_meals/blob/d16d4ca81d4292a9a6b3bd8b266a547f8e7a77e6/app/controllers/meals_controller.rb#L10
ここって
```
@user = @meal.user
```
でいいですよね？？

https://github.com/kosukein38/training_and_meals/blob/d16d4ca81d4292a9a6b3bd8b266a547f8e7a77e6/app/controllers/meals_controller.rb#L35

こちらはbefore_actionで呼んだほうがいいですね

https://github.com/kosukein38/training_and_meals/blob/d16d4ca81d4292a9a6b3bd8b266a547f8e7a77e6/app/services/meal_search_service.rb#L28

サービスクラスでまとめるより、DeepLやAPI-Ninjas問い合わせ用のクラスまたはモジュールを作るとそれぞれのモジュールの独立性が高くなるので汎用性が高くなるかと思います。またHTTPリクエストはFaradayを使うともう少しすっきり書けますよ。

* テストも書かれているようなので、あとはREADMEにスクショの画像入れたり、サービスの使い方なんかを入れると就活でもウケはよくなるかなと思います。

**Comment by kosukein38** [comment]
@hisaju ひさじゅさん！ありがとうございます。

> 筋トレと食事の関連性が薄い（別のサービスが2つ入ってる）印象だったので、組み合わせたカロリー計算などを入れることで連動するような筋トレと食事を登録するメリットが作れるといいのかなと思いました。
UIもユーザの導線を考えて自然と筋トレと食事の両方を登録できるようなカスタマージャーニーが作れるといいですね。

これについては、自分も２つの投稿がうまく連動するような仕組みを作りたいなと思っていました。カロリーもそうですし、筋トレの投稿したらモーダルで筋トレのレコメンド（煽り？）をするとか、双方絡み合うような使い方を実現できるようにしたいと思います。
コードレビューについてもありがとうございました🙏反映します！！
